# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  terraform-validations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Init 
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.0
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "./test/"
          tf_actions_comment: true

      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.0
          tf_actions_subcommand: "validate"
          tf_actions_working_dir: "./test/"
          tf_actions_comment: true
